spring.application.name=EorzeaEmporiumAPI
spring.datasource.url=jdbc:h2:file:/data/eedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=Passw0rd
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB